### ISSUE TITLE
Allow :tell to long-afk members.

### ISSUE THREAD

**Issue by TrentonOfCalref** [sylae/ligrev#27] opened 2015-12-13 16:56 UTC
- :tell afk support for people who rarely log off but use the /away function
- ~~auto kick system for thynar that kicks him if he posts a trigger word (ie, Christina, Emily, Cousin, Fleshlight)~~
- ~~Promotion of Trenton. to Head Administrator and overthrow of the Tyrant Queen, Sylae~~

**Comment by sylae** [comment] 2016-03-05 08:08
So in the field this edit seems to be working fine--there are a couple small issues but the big one is that it will send a :tell to afk people on connection. The problem is, presence stanzas (at least on ejabberd) don't indicate that the MUC user was already logged in; to Ligrev it appears that she entered an empty room, and then a bunch of people just show up!

The best solution would be to just not process :tell messages for the first couple seconds of joining the room, but that feels a bit hackey. Especially on a laggy connection or a popular MUC room, it could take more than that period to transmit all the existing members.

**Comment by sylae** [comment] 2016-03-27 10:06
Okay, so besides the "sends tell messages on startup" and the "will let tell messages get set after logging in but before the recipient has done anything" issues, everything seems to be fine. I just pushed a fix for the former, the latter is...not a dealbreaker, but certainly not ideal. It's gonna get forked to its own issue though.

**Closed by sylae** 2016-03-27 10:06 UTC
Labels: enhancement
